from id import Id
from instrument import Instrument
from license import License
from method import Method
from name import Name
from pages import Pages
from person import Person
from property import Property
from reference import Reference
from scalar import Scalar
from software import Software
from value import Value
